---
- name: Populate AD group list
  set_fact:
    role_ad_membership_allowed_group_list: '{{ role_ad_membership_allowed_group_list | default([]) + vars[item] }}'
  loop: "{{ vars.keys() | select('match', '^role_ad_membership_allowed_group_list_.*$') | list }}"

- name: Deploy configurations
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  notify:
    - restart_realmd
    - restart_sssd
    - restart_oddjobd
  loop:
    - { src: 'krb5.conf.j2', dest: '/etc/krb5.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'sssd.conf.j2', dest: '/etc/sssd/sssd.conf', owner: 'root', group: 'root', mode: '0600' }

...
