---
- name: Import tasks for prerequisites
  import_tasks: prerequisites.yml
  tags:
    - tag_role_ad_membership_prerequisites
    - tag_role_ad_membership_ad_join
    - tag_role_ad_membership_ad_leave

- name: Import tasks for joining the Windows AD
  import_tasks: ad_join.yml
  when:
    - role_ad_membership_register_discover_realm.stdout | length < 1
    - not role_ad_membership_leave_ad
    - not role_ad_membership_molecule_dummy
  tags:
    - tag_role_ad_membership_ad_join

- name: Import tasks for deploying configurations
  import_tasks: deploy_configurations.yml
  when:
    - not role_ad_membership_leave_ad
    - not role_ad_membership_molecule_dummy
  tags:
    - tag_role_ad_membership_deploy_configurations
    - tag_role_ad_membership_ad_join

- name: Import tasks for leaving the Windows AD
  import_tasks: ad_leave.yml
  when:
    - role_ad_membership_leave_ad
    - not role_ad_membership_molecule_dummy
  tags:
    - tag_role_ad_membership_ad_leave

...
