---
- name: Restart realmd service
  systemd:
    name: realmd
    state: restarted
    daemon_reload: True
    enabled: True
    masked: False
  listen: restart_realmd

- name: Stop realmd service
  systemd:
    name: realmd
    state: stopped
    enabled: False
  listen: stop_realmd

- name: Restart sssd service
  systemd:
    name: sssd
    state: restarted
    daemon_reload: True
    enabled: True
    masked: False
  listen: restart_sssd

- name: Stop sssd service
  systemd:
    name: sssd
    state: stopped
    enabled: False
  listen: stop_sssd

- name: Restart oddjobd service
  systemd:
    name: oddjobd
    state: restarted
    daemon_reload: True
    enabled: True
    masked: False
  listen: restart_oddjobd

- name: Clean all sss cache
  command: /usr/sbin/sss_cache -E
  args:
    warn: False
  changed_when: False
  listen: clean_cache

...
