---
- name: Restart sssd service
  systemd:
    name: sssd
    state: restarted
    daemon_reload: True
    enabled: True
    masked: False
  listen: restart_sssd

- name: Stop sssd service
  systemd:
    name: sssd
    state: stopped
    enabled: False
  listen: stop_sssd

- name: Clean all sss cache
  command: /usr/sbin/sss_cache -E
  args:
    warn: False
  listen: clean_sss_cache

...
