---
- name: Converge
  hosts: all
  become: True
  gather_facts: True
  tasks:
    - import_role:
        name: ansible_role_ad_membership
      vars:
        role_ad_membership_molecule_dummy: True

...
